### ISSUE TITLE
load unlabeled images

### ISSUE THREAD

**Issue by miaozhang0525** [soo89/CSD-RFCN#2]
In line 239 in train_csd:  "unlabel_imdb, unlabel_roidb, unlabel_ratio_list, unlabel_ratio_index = combined_roidb(args.imdb_name_unlabel)"

You will load the label information into the unlabel_imdb and  unlabel_roidb. It should not load the labeled information, isn't it??

I am very curious that why you load these label information of pascal-voc 2012 dataset.

Hope to get your early response.

Many thanks.

**Comment by soo89** [comment]
I used it to make the data loader easier.

However, before the training, the ground truth was deleted.

Please check L413, 414 in train_csd.py
