### ISSUE TITLE
why the consistency_loss is always 0??

### ISSUE THREAD

**Issue by miaozhang0525** [soo89/CSD-RFCN#3]
Hi, really appreciate for providing your codes.

However, when I reproduce your code., I just found the consistency loss is always zero. Do you know why this happens?

Many thanks.

**Comment by miaozhang0525** [comment]
I think the problem is that the line 111,  int(semi_check) in the rfcn_consistency.py

semi_check=[1,0,0,0]. So int(semi_check) should not work

**Comment by soo89** [comment]
Could you check output values and whether the second image batch is flipped?

I think that you missed the deepcopy.

**Comment by miaozhang0525** [comment]
> Could you check output values and whether the second image batch is flipped?
> 
> I think that you missed the deepcopy.

So in the training, the ['flipped'] for the labeled image and unlabeled image should be True?

**Comment by miaozhang0525** [comment]
Wher

> Could you check output values and whether the second image batch is flipped?
> 
> I think that you missed the deepcopy.

Where do I need to use the deepcopy? I did not found that you used this function in the train_csd.

Many many thanks!!

**Comment by soo89** [comment]
please check rfcn_consistency.py in /lib/model/rfcn/

I used "clone" many times to copy the variable.
[L96, im_data_flip = im_data.clone()]

**Comment by miaozhang0525** [comment]
So you mean that I need to change the clone() in rfcn_consistency.py to deepcopy?

Really thanks!

**Comment by soo89** [comment]
What I want to say that you need to check whether it is well flipped (original and flipped image) and outputs are different values.

**Comment by miaozhang0525** [comment]
> What I want to say that you need to check whether it is well flipped (original and flipped image) and outputs are different values.

OK! I got it! Really appreciate! One last simple and stupid question, so how do you determine which image's ['flipped'] should be true? Is it random? Sorry to bother you.  Many many thanks.

**Comment by soo89** [comment]
All samples are applied to horizontally flip. 
Please check our paper in detail.

**Comment by miaozhang0525** [comment]
> All samples are applied to horizontally flip.
> Please check our paper in detail.

I got it. Really thanks for your reply. That is very helpful to me.

I found that your use a function int(semi_check) in
https://github.com/soo89/CSD-RFCN/blob/45497e9b69ac6b0d962e1efbe6150ed8ca4188b0/lib/model/rfcn/rfcn_consistency.py#L111

However, the semicheck is an array-like ([1,0,0,0]) in your code, and using int (semi_check) will get an error. How to fix it? Can I simply use int (semi_check[0])??

Many thanks,
Sincerely.

**Comment by soo89** [comment]
I used 4 GPUs and 4 mini-batch.
In my case, there is only one value in semi_check.

**Comment by miaozhang0525** [comment]
> I used 4 GPUs and 4 mini-batch.
> In my case, there is only one value in semi_check.

I think I found the reason. Many thanks! Sincerely!
