### ISSUE TITLE
Request for the trained model on COCO or VOC

### ISSUE THREAD

**Issue by miaozhang0525** [soo89/CSD-RFCN#4]
Hi, 

Really thanks for your share these wonderful codes, and they really help me a lot. Currently, I am also working on this.

However, if you could provide a pretrained model (especially on COCO), it will greatly help us, and save our time. 

Is it possible to share a link of pretrained model on COCO? based RFCN is also OK.

Many many thanks.

Sincerely

**Comment by soo89** [comment]
I removed the trained model on my desktop.

I have a link for NeurIPS supplementary and you can get some trained model.

https://drive.google.com/drive/folders/1T6UrU4oU4gL9FCDAauCsHB0Z0gbcAHHp?usp=sharing

**Comment by miaozhang0525** [comment]
> I removed the trained model on my desktop.
> 
> I have a link for NeurIPS supplementary and you can get some trained model.
> 
> https://drive.google.com/drive/folders/1T6UrU4oU4gL9FCDAauCsHB0Z0gbcAHHp?usp=sharing

Thanks for your help. That is so nice of you. I got these models which are trained on labeled VOC and unlabeled COCO. Is that possible for you to share RFCN trained with labeled COCO? Or give some suggestions? 

That will be very helpful for me, and save my time.

Sincerely.

**Comment by soo89** [comment]
I don't have and it is not my contribution.

If necessary, please train the model yourself.
