### ISSUE TITLE
Ramp Up/Down weight for new datasets

### ISSUE THREAD

**Issue by ycliu93** [soo89/CSD-RFCN#5]
https://github.com/soo89/CSD-RFCN/blob/45497e9b69ac6b0d962e1efbe6150ed8ca4188b0/train_csd.py#L147

Hi @soo89 ,

Thanks for providing the code. I am curious about how to set up the ramp weight for consistency loss if I want to apply to a new dataset. 

Q1: Does "data_len" written in the rampweight mean that the training iterations for each epoch? 
Q2: If I want to apply this method to the new dataset (such as applying to other datasets), do you have any suggestions on setting this ramp weight? 

Thank you!

**Comment by ycliu93** [comment]
And, I try to understand your ramp scheduler. Does the following interpretation correct? 

**1. Iteration:  0 to ramp_up_end (2/7 x max_training iterations):**
ramp_weight = math.exp(-5 * math.pow((1 - iteration / ramp_up_end), 2)) * beta

**2. Iteration:  ramp_up_end (2/7 x max_training iterations) to ramp_down_start (6/7 x max_training iterations):**
ramp_weight = 1 * beta 

**3. Iteration:  ramp_down_start (6/7 x max_training iterations) to max_training_iterations:**
ramp_weight = math.exp(-12.5 * math.pow((1 - (iter_max - iteration) / (iter_max - ramp_down_start)), 2)) * beta

Thank you!

**Comment by soo89** [comment]
Yes, you are right.

We tried to follow the previous semi-supervised learning schedule.
(https://arxiv.org/abs/1610.02242) (Appendix A)

And, Our scheduling description is in the supplementary material.
(https://papers.nips.cc/paper/9259-consistency-based-semi-supervised-learning-for-object-detection)

**Comment by ycliu93** [comment]
Got it. Thanks for replying, @soo89  !
