### ISSUE TITLE
training device

### ISSUE THREAD

**Issue by Feobi1999** [soo89/CSD-RFCN#6]
Hello, I'd like to know the nvidia card you used during training. Because when I use this repo on other dataset, I got the out of memory error. But I also used 4 1080Ti and the bs=4, so I want to know that if there were some other mistakes I have made or just due to the limitation of memory.
(the dataset I use was cityscape which only contains 8 classes)

**Comment by soo89** [comment]
Same as yours, I used 4 GPUs (1080ti). However, there was little space on the GPU memory.  Please reduce the backbone network (resnet101 -> resnet50) or check your memory leak.
